const social = require('./social');

module.exports = [
  {
    platform: 'Upwork',
    platformColor: '#14a800',
    title: 'You will get RFE Response for your EB2 NIW Petition',
    sellerName: 'Rahat K.',
    sellerInitials: 'RK',
    rating: 4.8,
    reviewCount: 17,
    heroImage: '/images/portfolio/upwork-eb2niw/hero.jpg',
    heroLabel: 'EB-2 NIW',
    thumbnails: [
      '/images/portfolio/upwork-eb2niw/thumb-1.jpg',
      '/images/portfolio/upwork-eb2niw/thumb-2.jpg',
      '/images/portfolio/upwork-eb2niw/thumb-3.jpg',
      '/images/portfolio/upwork-eb2niw/thumb-4.jpg',
    ],
    price: 500,
    packageTitle: 'RFE Response',
    packageDescription: 'I will prepare a tailored response to RFE notice from USCIS for your EB-2 NIW.',
    deliveryDays: 6,
    revisions: 1,
    extras: [{ label: 'Number of Targeted Cover Letters', value: '1' }],
    ctaUrl: social.UPWORK_RFE_NIW_CATALOG_URL,
    ctaLabel: 'View Full Listing on Upwork',
    note: 'Upwork Payment Protection — fund the project upfront, Rahat gets paid once you’re satisfied with the work.',
  },
  {
    platform: 'Fiverr',
    platformColor: '#1dbf73',
    title: 'I will prepare a tailored response to your RFE from USCIS',
    sellerName: 'rahatkarim487',
    sellerInitials: 'RK',
    rating: null,
    reviewCount: null,
    heroImage: '/images/portfolio/fiverr-rfe/hero.webp',
    heroLabel: 'RFE Response',
    thumbnails: [
      '/images/portfolio/fiverr-rfe/thumb-1.jpg',
      '/images/portfolio/fiverr-rfe/thumb-2.jpg',
      '/images/portfolio/fiverr-rfe/thumb-3.jpg',
      '/images/portfolio/fiverr-rfe/thumb-4.jpg',
    ],
    price: null,
    packageTitle: 'RFE / NOID Response',
    packageDescription: 'A tailored response to your Request for Evidence from USCIS.',
    deliveryDays: null,
    revisions: null,
    extras: [],
    ctaUrl: social.FIVERR_RFE_GIG_URL,
    ctaLabel: 'View Full Gig on Fiverr',
    note: 'Fiverr Buyer Protection — pay only when you’re satisfied with the delivered work.',
  },
];
